parameters:
    haberberger_redis_storage.redisstorage.class: Haberberger\RedisStorageBundle\Services\RedisStorage
    haberberger_redis_storage.cachefactory.class: Haberberger\RedisStorageBundle\Services\CacheFactory

services:
    haberberger_redis_storage.redisstorage:
        class: %haberberger_redis_storage.redisstorage.class%
        arguments: [%redis.url%]
    redis:
      alias: haberberger_redis_storage.redisstorage

    haberberger_redis_storage.cachefactory:
            class: %haberberger_redis_storage.cachefactory.class%
            arguments: [@redis]
