parameters:
    haberberger_redis_storage.redisstorage.class: Haberberger\Bundle\RedisStorageBundle\Services\RedisStorage

services:
    haberberger_redis_storage.redisstorage:
        class: %haberberger_redis_storage.redisstorage.class%
        arguments: [%redis.url%]
    redis:
      alias: haberberger_redis_storage.redisstorage
